import { assertApprovedFetchUrl, classifyFetchResponse, isRobotsAllowed, parseJsonFeed, parseOfficialPage, parseRobotsTxt, parseSyndicationFeed, cosineSimilarity, textFeatureEmbedding, validateCandidate } from '@lo-lyfe/core';
import type { SupabaseClient } from '@supabase/supabase-js';

type Row={id:string;name:string;source_type:string;base_url:string;crawl_interval_minutes:number;allowed_hosts:string[];etag:string|null;consecutive_failures:number};
const UA='lo-lyfe-bot/1.0 (+https://github.com/jcltd303-hub/lo-lyfe)';
function extractCandidate(item:{title?:string;link?:string;description?:string}){const title=item.title?.trim(),claimUrl=item.link?.trim(),body=item.description?.trim();if(!title||!claimUrl||!body)return null;const deadline=body.match(/\b(20\d{2}-\d{2}-\d{2})\b/)?.[1];if(!deadline)return null;const lower=`${title} ${body}`.toLowerCase();const category:'settlement'|'refund'|'grant'|'coupon'|'freebie'|null=lower.includes('settlement')?'settlement':lower.includes('refund')?'refund':lower.includes('grant')?'grant':lower.includes('coupon')?'coupon':lower.includes('free')?'freebie':null;if(!category)return null;return{title:title.slice(0,500),summary:body.slice(0,10000),category,claimUrl,deadline,eligibilityText:body.slice(0,10000),proofRequired:[]}}
export async function ingestSource(admin:SupabaseClient,source:Row){
 const started=new Date().toISOString();const run=await admin.from('ingestion_runs').insert({source_id:source.id,started_at:started}).select('id').single();if(run.error)throw run.error;
 try{
  const crawl={...source,baseUrl:source.base_url,crawlIntervalMinutes:source.crawl_interval_minutes,allowedHosts:source.allowed_hosts,active:true};
  const target=assertApprovedFetchUrl(source.base_url,crawl);const robotsUrl=new URL('/robots.txt',target).href;
  const rr=await fetch(robotsUrl,{headers:{'User-Agent':UA},signal:AbortSignal.timeout(10000)});if(rr.ok){const rules=parseRobotsTxt((await rr.text()).slice(0,500001));if(!isRobotsAllowed(target.href,rules))throw new Error('ROBOTS_DENIED')}
  const headers:Record<string,string>={'User-Agent':UA,'Accept':'application/json, application/feed+json, application/rss+xml, application/atom+xml, text/html;q=0.8'};if(source.etag)headers['If-None-Match']=source.etag;
  const res=await fetch(target,{headers,redirect:'error',signal:AbortSignal.timeout(15000)});const decision=classifyFetchResponse(res.status,{etag:res.headers.get('etag')??undefined,'retry-after':res.headers.get('retry-after')??undefined},new Date(),source.consecutive_failures);
  if(decision.action!=='ingest'){const next=decision.action==='retry'?decision.retryAt:new Date(Date.now()+source.crawl_interval_minutes*60000).toISOString();await admin.from('sources').update({last_crawled_at:new Date().toISOString(),next_crawl_at:next,etag:'etag'in decision?decision.etag??source.etag:source.etag,consecutive_failures:decision.action==='retry'?source.consecutive_failures+1:0,...(decision.action==='disable'?{active:false,disabled_reason:'HTTP access disabled'}:{})}).eq('id',source.id);await admin.from('ingestion_runs').update({finished_at:new Date().toISOString(),outcome:decision.action,http_status:res.status,retry_at:decision.action==='retry'?decision.retryAt:null}).eq('id',run.data.id);return {accepted:0}}
  const raw=(await res.text()).slice(0,3000001);const ct=res.headers.get('content-type')??'';const items=ct.includes('json')?parseJsonFeed(raw):ct.includes('xml')||source.source_type==='rss'?parseSyndicationFeed(raw):parseOfficialPage(raw,target.href);
  let accepted=0;for(const item of items){if(!item.description)continue;try{const extracted=extractCandidate(item);if(!extracted)continue;const draft=validateCandidate(extracted,{id:source.id,allowedHosts:source.allowed_hosts});const existing=await admin.from('opportunities').select('id,title,summary,eligibility_text,canonical_url').in('status',['review','published']).limit(200);const vector=textFeatureEmbedding(`${draft.title} ${draft.summary} ${draft.eligibilityText}`);if((existing.data??[]).some(x=>x.canonical_url===draft.canonicalUrl||cosineSimilarity(vector,textFeatureEmbedding(`${x.title} ${x.summary} ${x.eligibility_text}`))>=0.92))continue;const ins=await admin.from('opportunities').insert({source_id:source.id,title:draft.title,summary:draft.summary,category:draft.category,claim_url:draft.claimUrl,canonical_url:draft.canonicalUrl,eligibility_text:draft.eligibilityText,deadline:draft.deadline,proof_required:draft.proofRequired,status:'review',content_embedding:vector,embedding_model:'lo-lyfe-feature-v1',embedded_at:new Date().toISOString()});if(!ins.error)accepted++}catch{/* unstructured/invalid facts stay out of catalog */}}
  const next=new Date(Date.now()+source.crawl_interval_minutes*60000).toISOString();await admin.from('sources').update({last_crawled_at:new Date().toISOString(),next_crawl_at:next,etag:res.headers.get('etag'),consecutive_failures:0,last_yield:accepted,robots_checked_at:new Date().toISOString()}).eq('id',source.id);await admin.from('ingestion_runs').update({finished_at:new Date().toISOString(),outcome:'success',http_status:res.status,candidates_found:items.length,candidates_accepted:accepted}).eq('id',run.data.id);return{accepted}
 }catch(e){const code=e instanceof Error?e.message.slice(0,120):'UNKNOWN';await admin.from('ingestion_runs').update({finished_at:new Date().toISOString(),outcome:code==='ROBOTS_DENIED'?'disabled':'failed',error_code:code}).eq('id',run.data.id);if(code==='ROBOTS_DENIED')await admin.from('sources').update({active:false,disabled_reason:'robots.txt disallows crawling',robots_checked_at:new Date().toISOString()}).eq('id',source.id);return{accepted:0,error:code}}
}